
name: Windows Server Setup

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v1

    - name: Run PowerShell script
      run: |
        $psversiontable
        Write-Host "Hello, World!"
        Get-ComputerInfo

    - name: Run Docker container
      run: |
        docker run --name myiisserver -d mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
